version: "3.7"

services:
  netifi-broker:
    image: netifi/broker:1.6.10
    networks:
      - netifi
    environment:
      BROKER_SERVER_OPTS: >
        '-Dnetifi.broker.ssl.disabled=true'
        '-Dnetifi.authentication.0.accessKey=9007199254740991'
        '-Dnetifi.authentication.0.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY='
        '-Dnetifi.broker.admin.accessKey=9007199254740991'
        '-Dnetifi.broker.admin.accessToken=kTBDVtfRBO4tHOnZzSyY5ym2kfY='
    ports:
      - 8001:8001
      - 7001:7001
      - 8101:8101
      - 6001:6001

networks:
  netifi: